### ISSUE TITLE
[5.3.x] Update SNAPSHOT version (5.3.1 Release)

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/tutorial-apps#114]
## Description
Update version to 5.3.2-SNAPSHOT in 5.3.x

## Possible Solutions
in .travis.yml 
Update from 5.3.1-SNAPSHOT to 5.3.2-SNAPSHOT

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [ ] 5.3.1(5.3.x)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btkobayashirun 
Sorry, please check #80 .

**Comment by btkobayashirun** [comment]
Leave a comment
