### ISSUE TITLE
Update version (2018 winter)

### ISSUE THREAD

**Issue by btkobayashirun** [terasolunaorg/tutorial-apps#136]
## Description
Update SNAPSHOT version for master, 5.4.x, and 5.3.x
Update travis.yml for master and 5.4.x
Change link to badge in readme for 5.4.x

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)
- [x] 5.4.1 (5.4.x)
- [ ] 5.3.2 (5.3.x )

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btyanagawamg Please check to required also for m-j, m-t.
