### ISSUE TITLE
Add eclipse directory explanation

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/tutorial-apps#140]
## Description
Add eclipse directory explanation for [docs/README.md](https://github.com/terasolunaorg/tutorial-apps/tree/master/docs)

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] master
- [x] 5.4.x
- [x] 5.3.x
- [x] 5.2.x
- [x] 5.1.x
- [x] 5.0.x
- [x] 1.0.x

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btyanagawamg 
Please backport to all versions.
