### ISSUE TITLE
Move login.jsp from just below webapp to webapp/WEB-INF/views/login

### ISSUE THREAD

**Issue by btkomatsubaratka** [terasolunaorg/tutorial-apps#174]
## Description
Reflect guideline change at terasolunaorg/guideline#3260

## Possible Solutions
Reflect guideline change at terasolunaorg/guideline#3260

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)
- [x] 5.4.2 (5.4.x)
- [x] 5.3.2 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)
- [x] 1.6.0 (m-j/master)
- [x] 1.6.0 (m-t/master) in #177

## Final Solution
Reflect guideline change at terasolunaorg/guideline#3260

## Issue Links
* terasolunaorg/guideline#3260
* terasolunaorg/guideline#3247

**Comment by yoshikawaa** [comment]
@btkomatsubaratka Please change the title appropriately!

**Comment by yoshikawaa** [comment]
@btkomatsubaratka For maintenance, it seems better to apply to all versions.
