### ISSUE TITLE
Separate pom.xml dependencies for app and common lib

### ISSUE THREAD

**Issue by bttanakagn** [terasolunaorg/tutorial-apps#21]
## Description
Refer to Issue Link

## Possible Solutions
Refer to Issue Link

## Affects Version/s
N/A

## Fix Version/s
5.2.0

## Issue Links
* https://github.com/terasolunaorg/terasoluna-gfw/issues/508

**Comment by bttanakagn** [comment]
I think that the file that shoud be modified is as below.
* secure-login-demo/scripts/secure-login-demo/secure-login-selenium/pom.xml.sed

**Comment by tiwatsuka** [comment]
This issue and https://github.com/terasolunaorg/tutorial-apps/issues/25 will be resolved at the same time.

**Comment by ikeyat** [comment]
tutorial-apps are generated from blank projects. All changes will be reflected via them without any changes in this repos.
