### ISSUE TITLE
Does not work to the screen to complete creation of new account

### ISSUE THREAD

**Issue by btyonezawaj** [terasolunaorg/tutorial-apps#213]
## Description
Does not work to the screen to complete creation of new account.

There was an error in the View URL set on the controller.

The valid URL is below.
```
return "redirect:/accounts/create?complete";
```
but, the following URL was set
```
return "redirect:/account/create?complete";
```

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.3.1.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)
- [x] 5.4.2 (5.4.x)
- [x] 5.3.2 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 1.6.0 (m-j/master)
- [x] 1.6.0 (m-t/master) ( in #189 )

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by btmorikawanoh** [comment]
1.6.0 (m-t/master)へは以下PR内で修正済みです。
https://github.com/terasolunaorg/tutorial-apps-macchinetta-thymeleaf/pull/8
