### ISSUE TITLE
Is it better to define the connection destination provided by the application to be tested in selenium.properties like selenium.serverUrl?

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/tutorial-apps#251]
## Description
Information on the application to be tested is written at [secure-login-infra.properties](https://github.com/terasolunaorg/tutorial-apps-macchinetta-thymeleaf/blob/master/secure-login-demo/src/secure-login-selenium/src/test/resources/META-INF/spring/secure-login-infra.properties) file exist in the selenium project now .

Is it better setting ?

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0 (master)
- [x] 5.4.2 (5.4.x)
- [x] 5.3.3 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 1.6.0 (m-j/master)
- [x] 1.6.0 (m-t/master)

## Final Solution
(To be written later by project member)

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btyanagawamg 
It seems... this issue is the purpose as follows:
Is it better to define the connection destination provided by the application to be tested in selenium.properties like selenium.serverUrl?
I don't think We would like to discuss itself whether to use infra.properties.
