### ISSUE TITLE
Integration Tests are required

### ISSUE THREAD

**Issue by btyoshikawaa** [terasolunaorg/tutorial-apps#27]
## Description

Now, we are testing tutorial-apps manually.
We should make test codes for integration test.
## Possible Solutions

Refer to Issue Link
## Affects Version/s
- 5.X.X.RELEASE
- 1.X.X.RELEASE
## Fix Version/s
- [x] 5.3.0
  - [x] todo
  - [x] todo-rest
  - [x] first-spring-security
  - [x] session-tutorial
## Issue Links
- #XXX

**Comment by ikeyat** [comment]
Are you talking about e2e testing?
Some apps implement selenium based e2e test codes.

**Comment by btyoshikawaa** [comment]
@ikeyat 
Yes. Some apps have e2e test codes, but other (perhaps following) apps not have them.
* first-spring-security 
* todo-rest
* todo

**Comment by btnoguchimnm** [comment]
@ikeyat 
Travis has a build target the archetype of lator 5.1.0.RELEASE .
But , in terasoluna-gfw-web-blank ( single project ) of 5.1.x , selenium is not defined in the pom.xml .
To add the e2e test , I add the definition of selenium in pom.xml .

I think that there is a need to consider adding a definition of selenium in pom.xml of terasoluna-gfw-web-blank of 5.1.x ( and 5.0.x ,  ... ).
