### ISSUE TITLE
[Dozer 6.x] Upgrade to Dozer 6.x

### ISSUE THREAD

**Issue by btshuugna** [terasolunaorg/tutorial-apps#316]
## Description
Since the specification of the dozer has been changed, updated dozer-core package name as follows.

From:
 org.dozer

to:
 com.github.dozermapper.core

## Possible Solutions
(Please write ideas or candidates of solutions for the problem if you have)

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.5.0.RELEASE
- [x] m-j
- [x] m-t

## Issue Links
- terasolunaorg/terasoluna-gfw#831

**Comment by hirakuriy** [comment]
@btshuugna 
Please backport.

**Comment by btyanagawamg** [comment]
Finished .
