### ISSUE TITLE
Enhance travis ci script

### ISSUE THREAD

**Issue by ikeyat** [terasolunaorg/tutorial-apps#32]
## Description
- [ ] Add execution of unit test
- [x] Add execution of e2e test (selenium)
- [x] Update the target version to be tested 
  - 5.3.0-SNAPSHOT
  - 5.2.1-SNAPSHOT
  - 5.2.0-SNAPSHOT -> 5.2.0.RELEASE
  - 5.1.2-SNAPSHOT
  - 5.1.1-SNAPSHOT -> 5.1.1.RELEASE
## Issue Links
#15
#27

**Comment by btnoguchimnm** [comment]
I will close this issue, the issues of the below will be corresponded by #51 .
