### ISSUE TITLE
Specify version for "mvn archetype:generate"

### ISSUE THREAD

**Issue by bthayashidi** [terasolunaorg/tutorial-apps#49]
## Description
In maven-archetype-plugin:3.0.0, the behavior of the "archetypeCatalog" parameter has changed and it is no longer possible to directly specify the URL.
 Therefore, build fails because it can not find archetype-catalog.xml.

## Possible Solutions
 * Explicitly use maven-archetype-plugin:2.4
    In version 2.4, the archetypeCatalog parameter works as expected.
    ```console
    mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate
    ```

## Affects Tartget Version/s
* 5.2.x
* 5.1.x
* 5.0.x
* 1.0.x

## Issue Links
* https://github.com/terasolunaorg/guideline/issues/2523
* https://github.com/terasolunaorg/terasoluna-gfw-web-blank/issues/267
* https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank/issues/301

**Comment by btyoshikawaa** [comment]
This (using 2.4) is an interim solution... let's correct it later.
