### ISSUE TITLE
Update the travis.yml target version

### ISSUE THREAD

**Issue by btnoguchimnm** [terasolunaorg/tutorial-apps#52]
## Discription
Update the target version to be tested 
  - 5.4.0-SNAPSHOT
  - 5.3.1-SNAPSHOT
  - 5.3.0-SNAPSHOT -> 5.3.0.RELEASE
  - 5.2.2-SNAPSHOT
  - 5.2.1-SNAPSHOT -> 5.2.1.RELEASE

If it is unnecessary, delete the following targets
  - 5.2.0.RELEASE
  - 5.1.2-SNAPSHOT
  - 5.1.1.RELEASE
  - 5.1.0.RELEASE

## Possible Solutions
modify travis.yml (see Discription)

## Issue Links

**Comment by yoshikawaa** [comment]
Respond in #57
