### ISSUE TITLE
Remain unnecessary ".gitkeep".

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/tutorial-apps#79]
## Description
Remain unnecessary ".gitkeep".
Ex, https://github.com/terasolunaorg/tutorial-apps/tree/master/secure-login-demo/src/secure-login-selenium/src/test/java

## Possible Solutions
Search and remove it.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [ ] master
- [ ] 5.3.x
- [ ] 5.2.x
- [ ] 5.1.x
- [ ] 5.0.x
- [ ] 1.0.x

## Issue Links
* #XXX

**Comment by btyanagawamg** [comment]
2018/3/20

I checked all versions and recognized there is already no `.gitkeep` file in tutorial-apps repository .
I will close this ISSUE .
