### ISSUE TITLE
Re-check artifact version.

### ISSUE THREAD

**Issue by yoshikawaa** [terasolunaorg/tutorial-apps#80]
## Description
https://github.com/terasolunaorg/tutorial-apps/blob/master/pom.xml#L6
Artifact id is `5.3.0-SNAPSHOT`, but current master is `5.4.0-SNAPSHOT`. 

## Possible Solutions
Check and fix it.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] master
- [x] 5.3.x
- [x] 5.2.x
- [x] 5.1.x
- [x] 5.0.x
- [x] 1.0.x

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btkobayashirun Thanks!

**Comment by yoshikawaa** [comment]
Reopend. 5.0.x is wrong...

**Comment by btyanagawamg** [comment]
Fixed 5.0.x at #224 .
