### ISSUE TITLE
guideline uses  @Compare, but custom @Comfirm validation is used in secure-login-demo.

### ISSUE THREAD

**Issue by btkatoutmj** [terasolunaorg/tutorial-apps#94]
## Description
guideline uses  `@Compare`,but custom `@Comfirm` validation is used in secure-login-demo.
[guideline](http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/ja/Security/SecureLoginDemo.html#id26)
[secure-login-demo](https://github.com/terasolunaorg/tutorial-apps/blob/59750a1115a15d6cb7074884df8d23f252311e32/secure-login-demo/secure-login-web/src/main/java/org/terasoluna/securelogin/app/passwordchange/PasswordChangeForm.java#L28)

## Possible Solutions
Fix source code to use `@Compare`

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)

## Issue Links
* terasolunaorg/guideline#2728

**Comment by yoshikawaa** [comment]
@btkatoutmj @itouyun 
I think... it seems reasonable to correspond to 5.2.x, 5.1.x.

**Comment by itouyun** [comment]
@yoshikawaa @btkatoutmj 
Thanks. We will extend target of backport to 5.2.x, 5.1.x.

**Comment by yoshikawaa** [comment]
@btkatoutmj Good work!
